config/routes.rb
EpicodusOverflow::Application.routes.draw do
  devise_for :users
  resources :questions
  resources :answers
  resources :votes
  resources :comments
  
  root to: "questions#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, Comment
      can :update, Comment do |comment|
        comment.try(:user) == user
      end
      can :destroy, Comment do |comment|
        comment.try(:user) == user
      end
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base 
  belongs_to :user
  belongs_to :question
  has_many :votes
  has_many :comments, as: :commentable
  validates :content, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base 
  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  validates :content, presence: true
  validates :user_id, presence: true
  validates :commentable_id, presence: true
  validates :commentable_type, presence: true

  
  def question
    if commentable_type == "Question"
      self.commentable
    else
      self.commentable.question
    end    
  end
end

app/models/question.rb
class Question < ActiveRecord::Base 
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  validates :content, presence: true
  validates :title, presence: true, length: { maximum: 100 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers 
  has_many :votes   
  has_many :comments
  
  def admin?
    self.admin
  end   
end

app/models/vote.rb
class Vote < ActiveRecord::Base 
  belongs_to :user 
  belongs_to :answer

  validates_uniqueness_of(:user_id, { :scope => :answer_id })
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController 

  def new 
    @answer = Answer.new(question_id: params[:question_id], :user => current_user)
  end

  def create
    @answer = current_user.answers.new(answer_params)
    if @answer.save
      respond_to do |format|
        format.html { redirect_to question_path(@answer.question) }
        format.js
      end
    else 
      render 'new.js'
    end
  end



private
  def answer_params 
    params.require(:answer).permit(:user_id, :question_id, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new(commentable_id: params[:commentable_id], commentable_type: params[:commentable_type])
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to question_path(@comment.question) }
        format.js
      end
    else
      render 'new.js'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if current_user = @comment.user
      @comment.destroy
      render 'delete.js'
    else
      redirect_to question_path(@comment.parent_question)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    if can? :update, @comment
      render 'edit.js'
    else
      unauthorized!
    end
  end

  def update 
    @comment = Comment.find(params[:id])
    if can? :update, @comment
      @comment.update(comment_params)
      render 'update.js'
    else 
      unauthorized!
    end
  end

private
  def comment_params
    params.require(:comment).permit(:user_id, :commentable_id, :commentable_type, :content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @questions = Question.page(params[:page]).per_page(7)
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Your question has been successfully posted!"
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def destroy 
    @question = Question.find(params[:id])
    authorize! :delete, @question
    @question.destroy
    redirect_to root_path, notice: "Question successfully deleted."
  end

private

  def question_params
    params.require(:question).permit(:content, :user_id, :title)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @vote = current_user.votes.new(vote_params)
    if @vote.save
      redirect_to @vote.answer.question 
    else
      redirect_to @vote.answer.question, alert: "You can't vote twice on the same answer."
    end
  end

private
  def vote_params
    params.require(:vote).permit(:answer_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div id="answer-<%= object.id %>" class="row">
  <div class='columns small-1 center'>
    <%= link_to '', votes_path(vote: {answer_id: object.id}), class: "fis-thumb-up", method: 'post'%>
    <h4><%= object.votes.count %></h4>
  </div>
  <div class='columns small-11'>
    <div class="row">
      <p><%= object.content %></p>
    </div>
    <div class="row">
      <div class="small-2 columns"><%= link_to "Comment", new_comment_path(commentable_id: object.id, commentable_type: "Answer"),
                  class: "comment-button", remote: true %></div>
      <p class="text-right">
        <a><%= object.user.email %></a> - 
        <%= object.created_at.strftime("%A %B %-d at %I:%m") %>
      </p>
    </div>
      
    <div id="answer-comment-list-<%= object.id %>" class="comments">
      <% object.comments.each do |comment| %>
        <%= render 'comments/comment', object: comment %>
      <% end %>
    </div>
  </div>
  <hr class="min_margin">
</div>

app/views/answers/_new_answer_form.html.erb
<%= form_for @answer, id: "new_answer", remote: true do |f| %>
  <h3>Answer</h3>
  <%= render "shared/form_errors", object: @answer %>
  <%= f.hidden_field :question_id %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit "Post your answer", class: "button" %>
<% end %>

app/views/answers/create.js.erb
$('#new_answer').remove();
$('#answer-button').show();
$('#answer-list').append('<%= j render "answers/answer", object: @answer %>');
$('#answer-list h3').empty().append('<%= pluralize(@answer.question.answers.count, "Answer") %>');

app/views/answers/new.js.erb
<% if current_user %>
  $('#form').empty().append("<%= j render 'new_answer_form' %>");
<% else %>
  window.location.replace('<%= request.base_url %>/users/sign_in');
<% end %>

app/views/comments/_comment.html.erb
<div id="comment-<%= object.id %>">
  <hr class='min_margin'>
  <p class='min_margin'><span><%= object.content %></span> - 
    <a><%= object.user.email %></a> 
    <%= object.created_at.strftime("(%A %B %-d at %I:%m)") %>
    <% if can? :update, object %>
      <%= link_to '', edit_comment_path(object), class: 'fi-edit', remote: true %>
    <% end %>
    <% if can? :destroy, object %>
      <%= link_to '', comment_path(object), method: 'delete', class: 'fi-trash', remote: true %>
    <% end %>
  </p>
</div>

app/views/comments/_edit_comment.html.erb
<div id="edit-comment-view">
  <h3>Edit Comment</h3>
  <%= form_for comment, id: "edit_comment", remote: true do |f| %>
    <%= render "shared/form_errors", object: comment %>
    <%= f.hidden_field :commentable_id %>
    <%= f.hidden_field :commentable_type %> 
    <%= f.label :content %>
    <%= f.text_area :content %>
    <%= f.submit "Update", class: "button", method: "patch" %>
  <% end %>
</div>

app/views/comments/_new_comment_form.html.erb
<div id="new-comment-view">
  <h3>Comment</h3>
  <%= form_for @comment, id: "new_comment", remote: true do |f| %>
    <%= render "shared/form_errors", object: @comment %>
    <%= f.hidden_field :commentable_id %>
    <%= f.hidden_field :commentable_type %> 
    <%= f.label :content %>
    <%= f.text_area :content %>
    <%= f.submit "Post your comment", class: "button" %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#new-comment-view').remove();
<% if @comment.commentable_type == 'Question' %>
  $('#question-comment-list').append('<%= j render "comments/comment", object: @comment %>');
<% else %>
  $('#answer-comment-list-<%= @comment.commentable_id %>').append('<%= j render "comments/comment", object: @comment %>');
<% end %>
$('#ajax-flash').empty().append("<div class='alert-box success'>Comment successfully added!</div>").fadeOut(5000);

app/views/comments/delete.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/comments/edit.js.erb
<% if @comment.commentable_type == 'Question' %>
  $('#form').empty().append("<%= j render 'edit_comment', comment: @comment %>");
<% else %>
  $('#answer-comment-list-<%= @comment.commentable_id %>').append ("<%= j render 'edit_comment', comment: @comment %>");
<% end %>

app/views/comments/new.js.erb
<% if current_user %> 
  <% if @comment.commentable_type == 'Question' %>
    $('#form').empty().append("<%= j render('new_comment_form') %>");
  <% else %>
    $('#answer-comment-list-<%= @comment.commentable_id %>').empty().append ("<%= j render('new_comment_form') %>");
  <% end %>
<% else %>
  window.location.replace('<% request.base_url %>/users/sign_in');
<% end %>

app/views/comments/update.js.erb
$('#edit-comment-view').remove();
$('#comment-<%= @comment.id %>').children('p').first().children('span').first().empty().append('<%= @comment.content %>');

app/views/layouts/_navbar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Questions', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="left">
      <li class="divider">
      <li class="divider"></li>
    </ul>
    <ul class="right">
      <li class="divider"></li>
      <% if user_signed_in? %>
        <li><a>Logged in as: <%= current_user.email %></a></li>
        <li class="divider"></li>
        <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li class="active"><%= link_to 'Sign up', new_user_registration_path %></li>
        <li class="divider"></li>
        <li class="active"><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>
      <li class="divider"></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><![endif]-->
<html lang="en">
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Epicodus QA" %></title>

  	<%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'shared/flash_messages' %>
    <div id="ajax-flash"></div>

    <%= yield %>
  <script>
    $(document).foundation();
  </script>
  </body>
</html>

app/views/questions/index.html.erb
<div class="row">
	<h1 class="center">Epicodus Q & A</h1>
</div>
<div class="row">
  <div class="header-panel">
    <div class="row">
      <div class="large-3 small-5 columns">
        <p class="lead header-left"> This is a question and answer site for student's of Epicodus. Here's how it works:</p>
      </div>
      <div class="large-9 small-7 columns">
        <div class="large-4 small-12 columns">
          <h1 class="center"><i class="fia-question icon-large"></i></h1>
          <p class="lead">A student asks a question.</p>
        </div>
        <div class="large-4 small-12 columns">
          <h1 class="center"><i class="fi-idea icon-large"></i></h1>
          <p class="lead">Other students answer.</p>
        </div>
        <div class="large-4 small-12 columns">
          <h1 class="center"><i class="fis-thumb-up icon-large"></i></h1>
          <p class="lead">The best answers are voted up.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  
</div>
<div class="row">
  <div class="small-4 columns">
    <%= link_to "Ask a question", new_question_path, class: "button" %>
  </div>
  <div class="large-2 large-offset-6  small-5 columns">
    <h5><%= foundation_paginate @questions %></h5>
  </div>
</div>
<div class='row'>
  <ul class="no-bullet">
    <% @questions.each do |question| %>
      <li>
        <hr>
        <div class="row">
          <div class="large-2 small-offset-1 small-3 columns">
            <h3 class="subheader"><%= pluralize(question.answers.count, "Answer") %><h3>
          </div>
          <div class="large-9 small-8 columns">
            <div class="row">
              <h4 class="subheader"><%= link_to question.title, question_path(question) %></h4>
            </div>
            <div class="row">
              <p><%= question.user.email %> <%= question.created_at.strftime("Asked on %A %B %-d at %I:%m") %></p>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<div class="row">
  <h5><%= foundation_paginate @questions %></h5>
</div>

app/views/questions/new.html.erb
<div class="row">
	<h1 class="center">Enter your question</h1>
</div>
<div class="row">
	<%= form_for @question do |f| %>
		<div class="row">
			<div class="row">
		  	<%= render 'shared/form_errors', object: @question %>
		  </div>
		  <div class='row'>
		  	<%= f.label :title %>
		  </div>
		  <div class="row">
		  	<%= f.text_field :title %>
		  </div>
		  <div class="row">
		  	<%= f.label :content %>
		  </div>
		  <div class="row">
		  	<%= f.text_area :content %>
		  </div>
		  <div class="row">
		  	<%= f.submit "Post your question", class: "button" %>
			</div>
		</div>
	<% end %>
</div>

app/views/questions/show.html.erb
<div class="row">
  <h1 class="center"><%= @question.title %></h1>
</div>
<div id="question" class="row">
  <div class="row">
    <h3 id='question-title' class="subheader columns">
      <%= @question.title %>
      <% if can? :destroy, @question %>
        <%= link_to '', question_path(@question), method: "delete", class: "fi-trash" %> 
      <% end %>
    </h3>
    <h6 class="subheader">Asked by <%= @question.user.email %> at: <%= @question.created_at.strftime("%A %B %-d at %I:%m") %></h6>
  </div>
  <div class="row">
    <p><%= @question.content %>
  </div>
  <div class="row">
    <%= link_to "Answer",
                new_answer_path(question_id: @question.id),
                id: "answer-button",
                remote: true %> ||
    <%= link_to "Improve this question",
                new_comment_path(commentable_id: @question.id, commentable_type: "Question"),
                id: "question-comment-button",
                class: "comment-button",
                remote: true %>
  </div>
  <br>
  <div id="question-comment-list" class='row'>
    <% @question.comments.each do |comment| %>
      <%= render 'comments/comment', object: comment %>
    <% end %>
  </div>
  <div class='row'><hr class='min_margin'></div>
</div>

<div id="form" class="row"></div>

<section id="answer-list" class="answers row">
  <h3><%= pluralize(@question.answers.count, "Answer") %></h3>
  <% if @question.answers.any? %>
    <% @question.answers.each do |answer| %>
      <%= render 'answers/answer', object: answer %>
    <% end %>
  <% end %>
</section>

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] %> 
  <div class="alert-box"><%= notice %></div>
<% elsif flash[:alert] %>
  <div class="alert-box alert"><%= alert %></div>
<% elsif flash[:info] %>
  <div class="alert-box success"><%= info %></div>
<% end %>

app/views/shared/_form_errors.html.erb
<div class="form-errors large-offset-1 columns">
	<% if object.errors.any? %>
	  <ul>
	    <% object.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	<% end %>
</div>

app/views/shared/_sign_up_or_in.js.erb
$("body").append("<div class='alert alert-error'><p>Please <%= link_to 'sign up', sign_in_path %>.")